#!/bin/sh
#
# Perform necessary datadog-updater setup steps after package is installed.
#
# .deb: STEP 5 of 5

readonly BOOTSTRAP_INSTALLER=${INSTALL_DIR}/bin/installer/installer
readonly STABLE_INSTALLER=${PACKAGES_DIR}/datadog-installer/stable/bin/installer/installer
readonly PACKAGES_LOCK_DIR=/var/run/datadog-packages

bootstrap() {
    $BOOTSTRAP_INSTALLER bootstrap --package "datadog-installer" && \
    $STABLE_INSTALLER bootstrap
}

set -e
case "$1" in
    configure)
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
    ;;
esac

# Lock_dir is world read/write/x as any application with a tracer injected
# needs to write PID files
chmod 777 ${PACKAGES_LOCK_DIR}

# we currently allow failures to install the installer
(bootstrap) || exit_code=$?
if [ -n "$exit_code" ]; then
    echo "Failed to bootstrap the installer: $exit_code"
fi

exit 0
